name: spool_coder_app
description: A Flutter app for reading and programming BambuLab filament spools.
version: 0.1.0
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  get_it: ^8.2.0
  go_router: ^16.0.0
  shared_preferences: ^2.3.2
  settings_ui: ^2.0.2
  nfc_manager: ^4.0.2
  nfc_manager_ndef: ^1.0.1

  # Add other dependencies here as needed

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  test: ^1.24.0

flutter:
  uses-material-design: true
  generate: true

  # Add fonts here
  fonts:
    - family: Space Grotesk
      fonts:
        - asset: assets/fonts/SpaceGrotesk-Light.ttf
          weight: 300
        - asset: assets/fonts/SpaceGrotesk-Regular.ttf
          weight: 400
        - asset: assets/fonts/SpaceGrotesk-Medium.ttf
          weight: 500
        - asset: assets/fonts/SpaceGrotesk-Bold.ttf
          weight: 700

  # Add assets here if needed
  assets:
    - assets/logo/
