name: spool_coder_app
description: A Flutter app for reading and programming BambuLab filament spools.
version: 0.1.0
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get_it: ^7.2.0
  go_router: ^16.0.0

  # Add other dependencies here as needed

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
